export const GET_LOGIN_DATA = 'GET_LOGIN_DATA';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_SIGNUP_DATA = 'GET_SIGNUP_DATA';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SET_APP_STATE = 'SET_APP_STATE';
